trigger: none # We'll trigger this pipeline from GitHub Actions

parameters:
  - name: sample
    type: string
    default: ''

variables:
  - name: ACR_NAME
    value: alloysamples.azurecr.io

stages:
- stage: Setup
  jobs:
  - job: SetMatrix
    pool:
      vmImage: ubuntu-latest
    steps:
    - bash: |
        if [ "$(parameters.sample)" != "" ]; then
          if [[ "$(parameters.sample)" == ajo-* ]]; then
            echo "##vso[task.setvariable variable=ajo_matrix;isoutput=true]{\"include\":[{\"sample\":\"$(parameters.sample)\"}]}"
          elif [[ "$(parameters.sample)" == target-* ]]; then
            echo "##vso[task.setvariable variable=target_matrix;isoutput=true]{\"include\":[{\"sample\":\"$(parameters.sample)\"}]}"
          elif [[ "$(parameters.sample)" == media-* ]]; then
            echo "##vso[task.setvariable variable=media_matrix;isoutput=true]{\"include\":[{\"sample\":\"$(parameters.sample)\"}]}"
          fi
        else
          echo "##vso[task.setvariable variable=ajo_matrix;isoutput=true]{\"include\":[{\"sample\":\"ajo-content-cards\"},{\"sample\":\"ajo-in-app-messages\"},{\"sample\":\"ajo-personalization-client-side\"},{\"sample\":\"ajo-personalization-hybrid\"},{\"sample\":\"ajo-personalization-server-side\"},{\"sample\":\"ajo-proposition-interaction-tracking\"}]}"
          echo "##vso[task.setvariable variable=target_matrix;isoutput=true]{\"include\":[{\"sample\":\"target-personalization-client-side\"},{\"sample\":\"target-personalization-hybrid\"},{\"sample\":\"target-personalization-hybrid-spa\"},{\"sample\":\"target-personalization-server-side\"},{\"sample\":\"target-top-and-bottom\"}]}"
          echo "##vso[task.setvariable variable=media_matrix;isoutput=true]{\"include\":[{\"sample\":\"media-collection\"}]}"
        fi
      name: setMatrix

- stage: DeployAJO
  dependsOn: Setup
  condition: ne(dependencies.Setup.outputs['SetMatrix.ajo_matrix'], '')
  jobs:
  - job: DeployAJO
    strategy:
      matrix: $[ dependencies.Setup.outputs['SetMatrix.ajo_matrix'] ]
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'ACR-Connection'
        repository: '$(sample)'
        command: 'buildAndPush'
        Dockerfile: 'docker/ajo.yml'
        tags: |
          $(Build.BuildId)
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: 'Azure-Subscription-Connection'
        appName: 'ajo'
        containers: '$(ACR_NAME)/$(sample):$(Build.BuildId)'

- stage: DeployTarget
  dependsOn: Setup
  condition: ne(dependencies.Setup.outputs['SetMatrix.target_matrix'], '')
  jobs:
  - job: DeployTarget
    strategy:
      matrix: $[ dependencies.Setup.outputs['SetMatrix.target_matrix'] ]
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'ACR-Connection'
        repository: '$(sample)'
        command: 'buildAndPush'
        Dockerfile: 'docker/target.yml'
        tags: |
          $(Build.BuildId)
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: 'Azure-Subscription-Connection'
        appName: 'target-sample'
        containers: '$(ACR_NAME)/$(sample):$(Build.BuildId)'

- stage: DeployMedia
  dependsOn: Setup
  condition: ne(dependencies.Setup.outputs['SetMatrix.media_matrix'], '')
  jobs:
  - job: DeployMedia
    strategy:
      matrix: $[ dependencies.Setup.outputs['SetMatrix.media_matrix'] ]
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'ACR-Connection'
        repository: '$(sample)'
        command: 'buildAndPush'
        Dockerfile: 'docker/media.yml'
        tags: |
          $(Build.BuildId)
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: 'Azure-Subscription-Connection'
        appName: 'media-sample'
        containers: '$(ACR_NAME)/$(sample):$(Build.BuildId)'