name: Trigger Azure Pipeline for Alloy Samples

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      sample:
        description: 'Specific sample to deploy (leave empty to deploy all)'
        required: false
        type: choice
        options:
          - ajo-content-cards
          - ajo-in-app-messages
          - ajo-personalization-client-side
          - ajo-personalization-hybrid
          - ajo-personalization-server-side
          - ajo-proposition-interaction-tracking
          - target-personalization-client-side
          - target-personalization-hybrid
          - target-personalization-hybrid-spa
          - target-personalization-server-side
          - target-top-and-bottom
          - media-collection

env:
  AZURE_DEVOPS_ORGANIZATION: mowla
  AZURE_DEVOPS_PROJECT: alloysample

jobs:
  trigger-azure-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Azure Pipeline
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: 'https://dev.azure.com/${{ env.AZURE_DEVOPS_ORGANIZATION }}/${{ env.AZURE_DEVOPS_PROJECT }}'
          azure-pipeline-name: 'adobe.alloy-samples'
          azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
        env:
          sample: ${{ github.event.inputs.sample }}